# Generated by Django 5.2 on 2025-05-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimientos',
            new_name='Movimiento',
        ),
    ]
