# Generated by Django 5.2 on 2025-05-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='descripcion',
        ),
    ]
