# Generated by Django 5.2 on 2025-05-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='usuarios.persona'),
        ),
    ]
